export const currencyOptions = [
  { code: "KES", label: "KES - Kenyan Shilling", symbol: "KSh" },
  { code: "USD", label: "USD - United States Dollar", symbol: "$" },
  { code: "AED", label: "AED - United Arab Emirates Dirham", symbol: "د.إ." },
  { code: "AFN", label: "AFN - Afghan Afghani", symbol: "؋" },
  { code: "ALL", label: "ALL - Albanian Lek", symbol: "L" },
  { code: "AMD", label: "AMD - Armenian Dram", symbol: "դր" },
  { code: "ANG", label: "ANG - Netherlands Antillean Guilder", symbol: "ƒ" },
  { code: "AOA", label: "AOA - Angolan Kwanza", symbol: "Kz" },
  { code: "ARS", label: "ARS - Argentine Peso", symbol: "$" },
  { code: "AUD", label: "AUD - Australian Dollar", symbol: "$" },
  { code: "AWG", label: "AWG - Aruban Florin", symbol: "ƒ" },
  { code: "AZN", label: "AZN - Azerbaijani Manat", symbol: "₼" },
  {
    code: "BAM",
    label: "BAM - Bosnia and Herzegovina Convertible Mark",
    symbol: "КМ",
  },
  { code: "BBD", label: "BBD - Barbadian Dollar", symbol: "$" },
  { code: "BDT", label: "BDT - Bangladeshi Taka", symbol: "৳" },
  { code: "BGN", label: "BGN - Bulgarian Lev", symbol: "лв." },
  { code: "BHD", label: "BHD - Bahraini Dinar", symbol: "د.ب." },
  { code: "BIF", label: "BIF - Burundian Franc", symbol: "FBu" },
  { code: "BMD", label: "BMD - Bermudian Dollar", symbol: "$" },
  { code: "BND", label: "BND - Brunei Dollar", symbol: "$" },
  { code: "BOB", label: "BOB - Bolivian Boliviano", symbol: "Bs." },
  { code: "BRL", label: "BRL - Brazilian Real", symbol: "R$" },
  { code: "BSD", label: "BSD - Bahamian Dollar", symbol: "$" },
  { code: "BTN", label: "BTN - Bhutanese Ngultrum", symbol: "Nu." },
  { code: "BWP", label: "BWP - Botswana Pula", symbol: "P" },
  { code: "BYN", label: "BYN - Belarusian Ruble", symbol: "руб." },
  { code: "BZD", label: "BZD - Belize Dollar", symbol: "$" },
  { code: "CAD", label: "CAD - Canadian Dollar", symbol: "$" },
  { code: "CDF", label: "CDF - Congolese Franc", symbol: "₣" },
  { code: "CHF", label: "CHF - Swiss Franc", symbol: "₣" },
  { code: "CKD", label: "CKD - Cook Islands Dollar", symbol: "$" },
  { code: "CLP", label: "CLP - Chilean Peso", symbol: "$" },
  { code: "CNY", label: "CNY - Chinese Yuan", symbol: "¥元" },
  { code: "COP", label: "COP - Colombian Peso", symbol: "$" },
  { code: "CRC", label: "CRC - Costa Rican Colon", symbol: "₡" },
  { code: "CUC", label: "CUC - Cuban convertible Peso", symbol: "$" },
  { code: "CUP", label: "CUP - Cuban Peso", symbol: "₱" },
  { code: "CVE", label: "CVE - Cabo Verdean Escudo", symbol: "$" },
  { code: "CZK", label: "CZK - Czech Koruna", symbol: "Kč" },
  { code: "DJF", label: "DJF - Djiboutian Franc", symbol: "ف.ج." },
  { code: "DKK", label: "DKK - Danish Krone", symbol: "kr." },
  { code: "DOP", label: "DOP - Dominican Peso", symbol: "$" },
  { code: "DZD", label: "DZD - Algerian Dinar", symbol: "د.ج." },
  { code: "EGP", label: "EGP - Egyptian Pound", symbol: "ج.م." },
  { code: "EHP", label: "EHP - Sahrawi Peseta", symbol: "Ptas." },
  { code: "ERN", label: "ERN - Eritrean Nakfa", symbol: "ناكفا" },
  { code: "ETB", label: "ETB - Ethiopian Birr", symbol: "ብር" },
  { code: "EUR", label: "EUR - Euro", symbol: "€" },
  { code: "FJD", label: "FJD - Fijian Dollar", symbol: "$" },
  { code: "FKP", label: "FKP - Falkland Islands Pound", symbol: "£" },
  { code: "FOK", label: "FOK - Faroese Króna", symbol: "kr" },
  { code: "GBP", label: "GBP - Pound Sterling", symbol: "£" },
  { code: "GEL", label: "GEL - Georgian Lari", symbol: "₾" },
  { code: "GGP", label: "GGP - Guernsey Pound", symbol: "£" },
  { code: "GHS", label: "GHS - Ghanaian Cedi", symbol: "₵" },
  { code: "GIP", label: "GIP - Gibraltar Pound", symbol: "£" },
  { code: "GMD", label: "GMD - Gambian Dalasi", symbol: "D" },
  { code: "GNF", label: "GNF - Guinean Franc", symbol: "FG" },
  { code: "GTQ", label: "GTQ - Guatemalan Quetzal", symbol: "$" },
  { code: "GYD", label: "GYD - Guyanese Dollar", symbol: "$" },
  { code: "HKD", label: "HKD - Hong Kong Dollar", symbol: "$" },
  { code: "HNL", label: "HNL - Honduran Lempira", symbol: "L" },
  { code: "HRK", label: "HRK - Croatian Kuna", symbol: "kn" },
  { code: "HTG", label: "HTG - Haitian Gourde", symbol: "G" },
  { code: "HUF", label: "HUF - Hungarian Forint", symbol: "Ft" },
  { code: "IDR", label: "IDR - Indonesian Rupiah", symbol: "Rp" },
  { code: "ILS", label: "ILS - Israeli new Shekel", symbol: "₪" },
  { code: "IMP", label: "IMP - Manx Pound", symbol: "£" },
  { code: "INR", label: "INR - Indian Rupee", symbol: "₹" },
  { code: "IQD", label: "IQD - Iraqi Dinar", symbol: "د.ع." },
  { code: "IRR", label: "IRR - Iranian Rial", symbol: "﷼" },
  { code: "ISK", label: "ISK - Icelandic Krona", symbol: "kr" },
  { code: "JEP", label: "JEP - Jersey Pound", symbol: "£" },
  { code: "JMD", label: "JMD - Jamaican Dollar", symbol: "$" },
  { code: "JOD", label: "JOD - Jordanian Dinar", symbol: "د.أ." },
  { code: "JPY", label: "JPY - Japanese Yen", symbol: "¥" },
  { code: "KGS", label: "KGS - Kyrgyzstani Som", symbol: "с" },
  { code: "KHR", label: "KHR - Cambodian Riel", symbol: "៛" },
  { code: "KID", label: "KID - Kiribati Dollar", symbol: "$" },
  { code: "KMF", label: "KMF - Comorian Franc", symbol: "CF" },
  { code: "KPW", label: "KPW - North Korean Won", symbol: "₩" },
  { code: "KRW", label: "KRW - South Korean Won", symbol: "₩" },
  { code: "KWD", label: "KWD - Kuwaiti Dinar", symbol: "د.ك." },
  { code: "KYD", label: "KYD - Cayman Islands Dollar", symbol: "$" },
  { code: "KZT", label: "KZT - Kazakhstani Tenge", symbol: "₸" },
  { code: "LAK", label: "LAK - Lao Kip", symbol: "₭" },
  { code: "LBP", label: "LBP - Lebanese Pound", symbol: "ل.ل." },
  { code: "LKR", label: "LKR - Sri Lankan Rupee", symbol: "රු or ரூ" },
  { code: "LRD", label: "LRD - Liberian Dollar", symbol: "$" },
  { code: "LSL", label: "LSL - Lesotho Loti", symbol: "L" },
  { code: "LYD", label: "LYD - Libyan Dinar", symbol: "ل.د." },
  { code: "MAD", label: "MAD - Moroccan Dirham", symbol: "د.م." },
  { code: "MDL", label: "MDL - Moldovan Leu", symbol: "L" },
  { code: "MGA", label: "MGA - Malagasy Ariary", symbol: "Ar" },
  { code: "MKD", label: "MKD - Macedonian Denar", symbol: "ден" },
  { code: "MMK", label: "MMK - Myanmar Kyat", symbol: "Ks" },
  { code: "MNT", label: "MNT - Mongolian Tögrög", symbol: "₮" },
  { code: "MOP", label: "MOP - Macanese Pataca", symbol: "MOP$" },
  { code: "MRU", label: "MRU - Mauritanian Ouguiya", symbol: "أ.م." },
  { code: "MUR", label: "MUR - Mauritian Rupee", symbol: "रु " },
  { code: "MVR", label: "MVR - Maldivian Rufiyaa", symbol: ".ރ" },
  { code: "MWK", label: "MWK - Malawian Kwacha", symbol: "MK" },
  { code: "MXN", label: "MXN - Mexican Peso", symbol: "$" },
  { code: "MYR", label: "MYR - Malaysian Ringgit", symbol: "RM" },
  { code: "MZN", label: "MZN - Mozambican Metical", symbol: "MT" },
  { code: "NAD", label: "NAD - Namibian Dollar", symbol: "$" },
  { code: "NGN", label: "NGN - Nigerian Naira", symbol: "₦" },
  { code: "NIO", label: "NIO - Nicaraguan Córdoba", symbol: "C$" },
  { code: "NOK", label: "NOK - Norwegian Krone", symbol: "kr" },
  { code: "NPR", label: "NPR - Nepalese Rupee", symbol: "रू" },
  { code: "NZD", label: "NZD - New Zealand Dollar", symbol: "$" },
  { code: "OMR", label: "OMR - Omani Rial", symbol: "ر.ع." },
  { code: "PAB", label: "PAB - Panamanian Balboa", symbol: "B/." },
  { code: "PEN", label: "PEN - Peruvian Sol", symbol: "S/." },
  { code: "PGK", label: "PGK - Papua New Guinean Kina", symbol: "K" },
  { code: "PHP", label: "PHP - Philippine Peso", symbol: "₱" },
  { code: "PKR", label: "PKR - Pakistani Rupee", symbol: "Rs" },
  { code: "PLN", label: "PLN - Polish Zloty", symbol: "zł" },
  { code: "PND", label: "PND - Pitcairn Islands Dollar", symbol: "$" },
  { code: "PRB", label: "PRB - Transnistrian Ruble", symbol: "р." },
  { code: "PYG", label: "PYG - Paraguayan Guaraní", symbol: "₲" },
  { code: "QAR", label: "QAR - Qatari Riyal", symbol: "ر.ق." },
  { code: "RON", label: "RON - Romanian Leu", symbol: "L" },
  { code: "RSD", label: "RSD - Serbian Dinar", symbol: "дин" },
  { code: "RUB", label: "RUB - Russian Ruble", symbol: "₽" },
  { code: "RWF", label: "RWF - Rwandan Franc", symbol: "R₣" },
  { code: "SAR", label: "SAR - Saudi Riyal", symbol: "ر.س." },
  { code: "SBD", label: "SBD - Solomon Islands Dollar", symbol: "$" },
  { code: "SCR", label: "SCR - Seychellois Rupee", symbol: "Rs" },
  { code: "SDG", label: "SDG - Sudanese Pound", symbol: "ج.س." },
  { code: "SEK", label: "SEK - Swedish Krona", symbol: "kr" },
  { code: "SGD", label: "SGD - Singapore Dollar", symbol: "$" },
  { code: "SHP", label: "SHP - Saint Helena Pound", symbol: "£" },
  { code: "SLL", label: "SLL - Sierra Leonean Leone", symbol: "Le" },
  { code: "SLS", label: "SLS - Somaliland Shilling", symbol: "Sl" },
  { code: "SOS", label: "SOS - Somali Shilling", symbol: "Ssh" },
  { code: "SRD", label: "SRD - Surinamese Dollar", symbol: "$" },
  { code: "SSP", label: "SSP - South Sudanese Pound", symbol: "SS£" },
  { code: "STN", label: "STN - Sao Tome and Príncipe Dobra", symbol: "Db" },
  { code: "SVC", label: "SVC - Salvadoran Colón", symbol: "₡" },
  { code: "SYP", label: "SYP - Syrian Pound", symbol: "ل.س." },
  { code: "SZL", label: "SZL - Swazi Lilangeni", symbol: "L" },
  { code: "THB", label: "THB - Thai Baht", symbol: "฿" },
  { code: "TJS", label: "TJS - Tajikistani Somoni", symbol: "SM" },
  { code: "TMT", label: "TMT - Turkmenistan Manat", symbol: "T" },
  { code: "TND", label: "TND - Tunisian Dinar", symbol: "د.ت." },
  { code: "TOP", label: "TOP - Tongan Paʻanga", symbol: "PT" },
  { code: "TRY", label: "TRY - Turkish Lira", symbol: "₺" },
  { code: "TTD", label: "TTD - Trinidad and Tobago Dollar", symbol: "$" },
  { code: "TVD", label: "TVD - Tuvaluan Dollar", symbol: "$" },
  { code: "TWD", label: "TWD - New Taiwan Dollar", symbol: "圓" },
  { code: "TZS", label: "TZS - Tanzanian Shilling", symbol: "TSh" },
  { code: "UAH", label: "UAH - Ukrainian Hryvnia", symbol: "грн" },
  { code: "UGX", label: "UGX - Ugandan Shilling", symbol: "Sh" },
  { code: "UYU", label: "UYU - Uruguayan Peso", symbol: "$" },
  { code: "UZS", label: "UZS - Uzbekistani Som", symbol: "сум" },
  { code: "VED", label: "VED - Venezuelan bolívar digital", symbol: "Bs." },
  { code: "VES", label: "VES - Venezuelan Bolívar Soberano", symbol: "Bs.F" },
  { code: "VND", label: "VND - Vietnamese Dong", symbol: "₫" },
  { code: "VUV", label: "VUV - Vanuatu Vatu", symbol: "VT" },
  { code: "WST", label: "WST - Samoan Tala", symbol: "ST" },
  { code: "XAF", label: "XAF - Central African CFA Franc BEAC", symbol: "Fr." },
  { code: "XCD", label: "XCD - East Caribbean Dollar", symbol: "$" },
  { code: "XOF", label: "XOF - West African CFA Franc BCEAO", symbol: "₣" },
  { code: "XPF", label: "XPF - CFP Franc (Franc Pacifique)", symbol: "₣" },
  { code: "YER", label: "YER - Yemeni Rial", symbol: "ر.ي." },
  { code: "ZAR", label: "ZAR - South African Rand", symbol: "R" },
  { code: "ZMW", label: "ZMW - Zambian Kwacha", symbol: "ZK" },
  { code: "ZWB", label: "ZWB - RTGS Dollar", symbol: "" },
  { code: "ZWL", label: "ZWL - Zimbabwean Dollar", symbol: "$" },
];

// Sample discount options
export const discountOptions = [
  { name: "Summer Sale 10th", value: 10 },
  { name: "Early Bird Special", value: 15 },
  { name: "Loyalty Discount", value: 20 },
  { name: "Bulk Order Discount", value: 25 },
  { name: "First Time Client", value: 10 },
  { name: "Holiday Special", value: 12 },
];

// Sample tax rates
export const taxRates = [
  { rate: 0, label: "No Tax (0%)" },
  { rate: 5, label: "Reduced Rate (5%)" },
  { rate: 16, label: "Standard Rate (10%)" },
  { rate: 20, label: "Higher Rate (20%)" },
];
